/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package fortex.com/fortex/fortexws/cmd */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "bridge_polling.go"

#include <string.h>
#include "FortexDefs.h"

#line 1 "cgo-generated-wrapper"

#line 3 "fortexws.go"

#include "FortexDefs.h"

#line 1 "cgo-generated-wrapper"

#line 5 "fortexws_mds.go"

#include "FortexDefs.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern MarketData* GetMarketData(void);
extern FortexObject GetMessageFromServer(void);
extern int GetMarketDataEx(void);
extern int GetMessageFromServerEx(void);
extern int ToInt(int index);
extern char* ToString(int index);
extern void ToStringEx(int index, char* buffer, int bufferSize);
extern double ToDouble(int index);
extern long long int ToLongLong(int index);
extern float ToFloat(int index);
extern void PutInt(int objType, int index, int val);
extern void PutString(int objType, int index, char* val);
extern void PutDouble(int objType, int index, double val);
extern void PutLongLong(int objType, int index, long long int val);
extern void PutFloat(int objType, int index, float val);
extern int ModifyOrderEx(char* account);
extern void SetLogPath(char* path);
extern void HighWaterMark(int value);
extern char* GetLastErrorMessage(void);
extern int GetState(void);
extern int Connect(void);
extern int Login(char* username, char* apiKey, char* password);
extern void Logout(void);
extern void Cleanup(void);
extern char* GetCurrentUser(void);
extern int SubscribeMarketData(Symbol sym, int mdType, int isUnsubscribe);
extern int SubscribeMarketDataEx(int index, char* symName, int mdType, int isUnsubscribe);
extern int QueryEvents(char* acc, char* fromTime, char* toTime, char** types, int typesCount);
extern int QueryTradeHistory(TradeHistoryRequest req);
extern int QueryChart(ChartRequest req);
extern int EnterDoneawayTrade(char* acct, char* symName, int direction, char* refTktNo, int side, double qty, double px);
extern void RegisterEventInitSequence(CBInitSequence cb);
extern void RegisterEventAccountInfo(CBAccountInfo cb);
extern void RegisterEventLogin(CBLogin cb);
extern void RegisterEventLogout(CBLogout cb);
extern void RegisterEventSymbolList(CBSymbolInfo cb);
extern void RegisterEventMarketData(CBMarketData cb);
extern void RegisterEventNetPosition(CBNetPosition cb);
extern void RegisterEventOpenOrder(CBOpenOrder cb);
extern void RegisterEventNetTicket(CBNetTicket cb);
extern void RegisterEventTicket(CBTicket cb);
extern void RegisterEventExecutionReport(CBExecutionReport cb);
extern void RegisterEventExecutionData(CBExecutionData cb);
extern void RegisterEventChartData(CBChartData cb);
extern void RegisterEventTradeHistory(CBTradeHistory cb);
extern void RegisterEventOrdRejectData(CBOrdRejectData cb);
extern void RegisterEventRejectData(CBRejectData cb);
extern void RegisterEventEvent(CBEvent cb);
extern void RegisterEventCheckWebServer(CBCheckWebServer cb);
extern void RegisterEventReloginToRest(CBReloginToRest cb);
extern void RegisterEventDepositeWithdrawn(CBDepositedWithdrawn cb);
extern void RegisterEventCertRejectData(CBCertRejectData cb);
extern void ReleaseFortexObject(FortexObject message);
extern void Init(char* address, char* pfxFile, char* pfxPass, int msgRecvType);
extern int PlaceMarketOrder(char* acct, int side, double qty, Symbol sym);
extern int PlaceMarketOrderEx(char* acct, int side, double qty, char* symName, int secType);
extern int PlaceLimitOrder(char* acct, int side, double qty, Symbol sym, double limitPx);
extern int PlaceLimitOrderEx(char* acct, int side, double qty, char* symName, int secType, double limitPx);
extern int PlaceStopOrder(char* acct, int side, double qty, Symbol sym, double stopPx);
extern int PlaceStopOrderEx(char* acct, int side, double qty, char* symName, int secType, double stopPx);
extern int PlaceThresholdOrder(char* acct, int side, double qty, Symbol sym, double upperBoundPx, double lowerBoundPx);
extern int PlaceThresholdOrderEx(char* acct, int side, double qty, char* symName, int secType, double upperBoundPx, double lowerBoundPx);
extern int CancelOrder(char* acct, char* origOrdUser, char* origOrdClOrder, int origOrdType, int origOrdSide, double origOrdQty, Symbol* origOrdSym, char* origOrExecDest, char* origOrdTag, int tif);
extern int CancelOrderEx(char* acct, char* origOrdUser, char* origOrdClOrder, int origOrdType, int origOrdSide, double origOrdQty, char* symName, int secType, char* origOrExecDest, char* origOrdTag, int tif);
extern int ModifyOrder(char* acct, Order ord);

#ifdef __cplusplus
}
#endif
